### ISSUE TITLE
More flexible test images

### ISSUE THREAD

**Issue by loa** [tomologic/wrench#27]
Currently only a single test image is supported which is based on rel or builder image. The image need to be rebuilt each time a change happens and implementing volumes for testing will get complex #12.

Proposed solution:
- Allow multiple test images with any name
- Don't base test images on builder or release image
- Utilize volumes to give access to build artifacts or source code from release/builder images to test image
- Allow run commands to specify in what image to run command _(rel, builder, any test image)_

```
Dockerfile.acceptance
Dockerfile.syntax
Dockerfile.foobar
```

wrench.yml

```
Images:
  acceptance:
    Volumes:
      code-dir:
         Source: builder
         Volume: /usr/app/src:/usr/app/src
Run:
  acceptance-test:
    Cmd: flake8 . -v
    Image: acceptance
```
